/**
 * Wordle API
 * API para jugar Wordle, un juego de adivinanzas de palabras de 5 letras.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StartGameRequest { 
    /**
     * Nivel de dificultad del juego
     */
    difficulty?: StartGameRequest.DifficultyEnum;
}
export namespace StartGameRequest {
    export type DifficultyEnum = 'easy' | 'medium' | 'hard';
    export const DifficultyEnum = {
        Easy: 'easy' as DifficultyEnum,
        Medium: 'medium' as DifficultyEnum,
        Hard: 'hard' as DifficultyEnum
    };
}


